defaults: &defaults

  domain: itriagehealth.com
  repositories_path: /Users/ryan/dev/healthagen

  hipchat:
    token: aa374f31a35ed5d208d22331a2ebc7
    name: iTriage Bot

  hubot_token: 2eaf172f901f24feb311527c3ddc04

  redis:
    host: localhost
    port: 6397


development:
  <<: *defaults

test:
  <<: *defaults

